name: Openwrt Build Bot
on:
  schedule:
  - cron: 18 * * * *
  push:
    branches:
      - main

jobs:
  check:
    name: Check new version of mihomo
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: MetaCubeX/mihomo
          BRANCH: main
